version: '2'

services:
    php:
        build: '.'
        links:
            - database
        env_file: support/env/dev.env
        volumes:
            - '.:/srv'

    front:
        build: 'front'
        ports:
            - 0.0.0.0:8080:80

    database:
        image: postgres:9.4
        env_file: .env
        volumes:
            - "dbdata:/var/lib/postgresql"

volumes:
    dbdata:
        driver: local
